language: node_js

node_js:
  - stable

install:
  - npm install
  - npm install -g firebase-tools

script:
  - until firebase setup:emulators:firestore; do echo Retrying firestore setup...; done
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"