# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
- group: Firebase

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g firebase-tools
  displayName: 'npm install'

- script: |
    firebase setup:emulators:firestore
    firebase list --token $(FIREBASE_CI_TOKEN)
  displayName: 'setup emulator and login to firebase'

- script: |
    firebase emulators:exec --only firestore --project $(FIREBASE_PROJECT_ID) \"npm run cover-all\"
  displayName: 'run tests with coverage'

- script: |
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  displayName: 'send coverage data to Coveralls'