# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
- group: Settings

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g firebase-tools
  displayName: 'npm install'

- script: |
    firebase setup:emulators:firestore
    firebase --token $(FIREBASE_CI_TOKEN) --project $(FIREBASE_PROJECT_ID) emulators:exec --only firestore "npm run cover-all"
  displayName: 'setup emulator and run tests'

- script: |
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  env:
    COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
  displayName: 'send coverage data to Coveralls'